### PR TITLE
add NIOAPNS dep

### PR DESCRIPTION
**Pull request by tanner0101**

### CODE REVIEW

**Comment by tanner0101** [comment]
@kylebrowning looks like an issue with `CNIOOpenSSL` on Linux: 

```
<unknown>:0: warning: missing submodule 'CNIOOpenSSL'
/root/project/.build/checkouts/swift-nio-http2-apns/Sources/NIOAPNS/APNSConfig.swift:11:8: error: missing required module 'CNIOOpenSSL'
import NIOOpenSSL
       ^
/root/project/.build/checkouts/swift-nio-http2-apns/Sources/NIOAPNS/JWT.swift:133:99: error: use of undeclared type 'ECDSA_SIG'
        let sig = signature.withUnsafeBytes { (ptr: UnsafePointer<UInt8>) -> UnsafeMutablePointer<ECDSA_SIG> in
                                                                                                  ^~~~~~~~~
/root/project/.build/checkouts/swift-nio-http2-apns/Sources/NIOAPNS/JWT.swift:133:47: error: 'UnsafePointer<UInt8>' is not convertible to 'UnsafePointer<_>'
        let sig = signature.withUnsafeBytes { (ptr: UnsafePointer<UInt8>) -> UnsafeMutablePointer<ECDSA_SIG> in
                                              ^

Exited with code 1
```

Probably because `CNIOOpenSSL` isn't listed as a dependency here: https://github.com/kylebrowning/swift-nio-http2-apns/blob/master/Package.swift#L33

**Comment by kylebrowning** [comment]
@tanner0101 Try now?

**Comment by tanner0101** [comment]
Hmm, now this which makes sense:
```
Resolving https://github.com/apple/swift-nio-http2 at 0.1.0
'swift-nio-http2-apns' /root/project/.build/checkouts/swift-nio-http2-apns: error: product dependency 'CNIOOpenSSL' not found
Exited with code 1
```
Maybe it's just missing an `import CNIOOpenSSL` in `APNSConfig.swift`?

**Comment by kylebrowning** [comment]
Hrmm, @tanner0101 what about now?

**Comment by tanner0101** [comment]
This should do the trick: https://github.com/kylebrowning/swift-nio-http2-apns/pull/2

**Comment by kylebrowning** [comment]
@tanner0101 Okay merged. You can remove my addition of the openssl package as Im pretty sure SPM handles that for us!

**Comment by tanner0101** [comment]
Hmm seems like everything is working, we're just missing `ECDSA_SIG` on Linux for some reason. I wonder if it's a discrepancy between LibreSSL and real OpenSSL versions?

**Comment by kylebrowning** [comment]
What version of openssl is it getting?

**Comment by tanner0101** [comment]
Ah, looks like that struct was made private as a part of OpenSSL 1.1, like everything else.

https://github.com/qtumproject/qtum/issues/382#issuecomment-395750137

Doing this in the `shim.h` might fix it:
```c
#include <openssl/opensslv.h>

#if OPENSSL_VERSION_NUMBER >= 0x10100000L
typedef struct ECDSA_SIG_st {
    BIGNUM *r;
    BIGNUM *s;
} ECDSA_SIG;
#endif
```

**Comment by kylebrowning** [comment]
Roger, trying

**Comment by kylebrowning** [comment]
@tanner0101 back in your court. It compiles now.

**Comment by tanner0101** [comment]
woot, finally :)

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1010 coins.

**Pull request merged**
